[package]
name = "playsoundrust"
version = "0.1.0"
edition = "2024"

[dependencies]
tray-icon = "0.21"
rodio = "0.21"
image = "0.25"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-app-kit = "0.3"
